#!/bin/bash
./validate_prereqs.sh

MANAGEMENT=localhost:3003
PROVIDER_USER_REGISTRY=api-manager-lur
ADMIN_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI4ZWUwNzg4YS0yYzRhLTQ4MmItOGFkNS02NDUwMmZjZTI5NGMiLCJuYW1lc3BhY2UiOiIxYmRmMTA0YS1lNWM5LTRlOWQtYmU5Mi1hNDQ0ZjRlNjA4ZGI6NzI2MDdmMTctODQxOC00MzJiLTgyNGItM2Q3YmJlZDE3M2IzOjc4YWNhYzU5LWU2NzAtNDczZS05ZmU4LTQwNTZkMjY1YTQ3ZSIsImF1ZCI6Ii9hcGkvY2xvdWQvcmVnaXN0cmF0aW9ucy9mZjJhYWNhYS03MjAzLTRmMTEtYmViOS1jNDIzYTA0NmZiZmMiLCJzdWIiOiIvYXBpL3VzZXItcmVnaXN0cmllcy8xYmRmMTA0YS1lNWM5LTRlOWQtYmU5Mi1hNDQ0ZjRlNjA4ZGIvNzI2MDdmMTctODQxOC00MzJiLTgyNGItM2Q3YmJlZDE3M2IzL3VzZXJzLzc4YWNhYzU5LWU2NzAtNDczZS05ZmU4LTQwNTZkMjY1YTQ3ZSIsImlzcyI6IklCTSBBUEkgQ29ubmVjdCIsImV4cCI6MTU3NTQ0MjY4NywiaWF0IjoxNTc1NDEzODg3LCJncmFudF90eXBlIjoicGFzc3dvcmQiLCJ1c2VyX3JlZ2lzdHJ5X3VybCI6Ii9hcGkvdXNlci1yZWdpc3RyaWVzLzFiZGYxMDRhLWU1YzktNGU5ZC1iZTkyLWE0NDRmNGU2MDhkYi83MjYwN2YxNy04NDE4LTQzMmItODI0Yi0zZDdiYmVkMTczYjMiLCJyZWFsbSI6ImFkbWluL2RlZmF1bHQtaWRwLTEiLCJ1c2VybmFtZSI6ImFkbWluIiwiaWRfdG9rZW4iOiJleUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKbWFYSnpkRjl1WVcxbElqb2lRMnh2ZFdRaUxDSnNZWE4wWDI1aGJXVWlPaUpQZDI1bGNpSXNJblZ6WlhKZmFXUWlPaUkzTVRBME4yWXhOQzFqT0RjeUxUUmhaVFF0WW1FeE15MHhZVGt3T1RkaU1qVXpZek1pTENKMWMyVnlibUZ0WlNJNkltRmtiV2x1SWl3aWFXRjBJam94TlRjMU5ERXpPRGczZlEudk5XNHl1cmpoRmNYVW8wZ2NSX19UenVhYkF0RTVHanVkMkxhZy05d0J0dyIsInNjb3BlcyI6WyJjbG91ZDp2aWV3IiwiY2xvdWQ6bWFuYWdlIiwicHJvdmlkZXItb3JnOnZpZXciLCJwcm92aWRlci1vcmc6bWFuYWdlIiwib3JnOnZpZXciLCJvcmc6bWFuYWdlIiwiZHJhZnRzOnZpZXciLCJkcmFmdHM6ZWRpdCIsImNoaWxkOnZpZXciLCJjaGlsZDpjcmVhdGUiLCJjaGlsZDptYW5hZ2UiLCJwcm9kdWN0OnZpZXciLCJwcm9kdWN0OnN0YWdlIiwicHJvZHVjdDptYW5hZ2UiLCJhcHByb3ZhbDp2aWV3IiwiYXBwcm92YWw6bWFuYWdlIiwiYXBpLWFuYWx5dGljczp2aWV3IiwiYXBpLWFuYWx5dGljczptYW5hZ2UiLCJjb25zdW1lci1vcmc6dmlldyIsImNvbnN1bWVyLW9yZzptYW5hZ2UiLCJhcHA6dmlldzphbGwiLCJhcHA6bWFuYWdlOmFsbCIsIm15OnZpZXciLCJteTptYW5hZ2UiLCJ3ZWJob29rOnZpZXciXX0.LKvdGC67rKA0clOxZ2s6yYEKPRoImfyBngtH-X56_mg
PROVIDER_IDP=provider/default-idp-2
PROVIDER_USERNAME=steve5
PROVIDER_PASSWORD=8iron-hide
PROVIDER_EMAIL=steve1@apic.com
PROVIDER_FIRSTNAME=Steve1
PROVIDER_LASTNAME=Owner


userURL=`curl -X POST https://$MANAGEMENT/api/user-registries/admin/$PROVIDER_USER_REGISTRY/users -s -k \
	      -H "Content-Type:application/json" \
     	      -H "Accept:application/json" \
	      -H "Authorization:Bearer $ADMIN_TOKEN" \
	      -d "{ \"username\": \"$PROVIDER_USERNAME\",
              	    \"password\": \"$PROVIDER_PASSWORD\",
                    \"email\": \"$PROVIDER_EMAIL\",
                    \"first_name\": \"$PROVIDER_FIRSTNAME\",
                    \"last_name\": \"$PROVIDER_LASTNAME\" }" | jq '.url' `

echo User url: $userURL
